"""Seed module_units from the syllabus markdown.

Usage:
    cd backend
    uv run python scripts/seed_units_from_syllabus.py

This script reads docs/syllabus_sante_publique_AOF.md and populates the
module_units table with per-module units (lessons + quiz + case study).

It is idempotent: running it multiple times will only update existing rows,
not create duplicates.
"""

from __future__ import annotations

import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import structlog
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker

from app.domain.models.module import Module
from app.domain.models.module_unit import ModuleUnit
from app.infrastructure.config.settings import get_settings

logger = structlog.get_logger()

SYLLABUS_UNITS: dict[int, list[dict]] = {
    1: [
        {
            "unit_number": "M01-U01",
            "title_fr": "Définitions et histoire de la santé publique",
            "title_en": "Definitions and history of public health",
            "description_fr": "Évolution de la santé publique, définitions OMS/Donaldson, cadre conceptuel moderne",
            "description_en": "Evolution of public health, WHO/Donaldson definitions, modern conceptual framework",
            "estimated_minutes": 45,
            "order_index": 1,
            "unit_type": "lesson",
            "books_sources": {"donaldson": ["Ch.1", "Ch.13"], "scutchfield": ["Ch.1", "Ch.2"]},
        },
        {
            "unit_number": "M01-U02",
            "title_fr": "Déterminants de santé et modèle Dahlgren-Whitehead",
            "title_en": "Health determinants and Dahlgren-Whitehead model",
            "description_fr": "Le modèle des déterminants sociaux de santé contextualisé Afrique de l'Ouest",
            "description_en": "Social determinants of health model contextualized for West Africa",
            "estimated_minutes": 50,
            "order_index": 2,
            "unit_type": "lesson",
            "books_sources": {"donaldson": ["Ch.1"], "scutchfield": ["Ch.3", "Ch.4"]},
        },
        {
            "unit_number": "M01-U03",
            "title_fr": "Fonctions essentielles de santé publique en AOF",
            "title_en": "Essential public health functions in West Africa",
            "description_fr": "Les 10 fonctions essentielles, cadre institutionnel OOAS/WAHO/CEDEAO",
            "description_en": "The 10 essential functions, WAHO/ECOWAS institutional framework",
            "estimated_minutes": 50,
            "order_index": 3,
            "unit_type": "lesson",
            "books_sources": {"donaldson": ["Ch.13"], "scutchfield": ["Ch.4"]},
        },
        {
            "unit_number": "M01-U04",
            "title_fr": "Quiz pratique : Fondements",
            "title_en": "Practice Quiz: Foundations",
            "description_fr": "Testez votre compréhension des fondements de la santé publique",
            "description_en": "Test your understanding of public health fundamentals",
            "estimated_minutes": 25,
            "order_index": 4,
            "unit_type": "quiz",
            "books_sources": {"donaldson": ["Ch.1", "Ch.13"], "scutchfield": ["Ch.1", "Ch.2", "Ch.3", "Ch.4"]},
        },
        {
            "unit_number": "M01-U05",
            "title_fr": "Étude de cas : Épidémie Ebola Guinée 2014",
            "title_en": "Case Study: Ebola Epidemic Guinea 2014",
            "description_fr": "Analyser les défaillances systémiques et proposer des mesures préventives",
            "description_en": "Analyze systemic failures and propose preventive measures",
            "estimated_minutes": 40,
            "order_index": 5,
            "unit_type": "case-study",
            "books_sources": {"donaldson": ["Ch.1", "Ch.13"], "scutchfield": ["Ch.1"]},
        },
    ],
    2: [
        {
            "unit_number": "M02-U01",
            "title_fr": "Types de données et sources en santé publique",
            "title_en": "Data types and sources in public health",
            "description_fr": "Données nominales, ordinales, continues, discrètes; sources DHIS2, DHS, SNIS",
            "description_en": "Nominal, ordinal, continuous, discrete data; DHIS2, DHS, NHIS sources",
            "estimated_minutes": 45,
            "order_index": 1,
            "unit_type": "lesson",
            "books_sources": {"triola": ["Ch.1", "Ch.2"], "scutchfield": ["Ch.13"]},
        },
        {
            "unit_number": "M02-U02",
            "title_fr": "Statistiques descriptives appliquées à la santé",
            "title_en": "Descriptive statistics applied to health",
            "description_fr": "Mesures de tendance centrale, dispersion, boxplots, valeurs aberrantes",
            "description_en": "Measures of central tendency, dispersion, boxplots, outliers",
            "estimated_minutes": 55,
            "order_index": 2,
            "unit_type": "lesson",
            "books_sources": {"triola": ["Ch.2", "Ch.3"]},
        },
        {
            "unit_number": "M02-U03",
            "title_fr": "Indicateurs de santé et interprétation",
            "title_en": "Health indicators and interpretation",
            "description_fr": "Taux, ratios, proportions; indicateurs clés RMNCH; introduction Excel/Sheets",
            "description_en": "Rates, ratios, proportions; key RMNCH indicators; intro Excel/Sheets",
            "estimated_minutes": 50,
            "order_index": 3,
            "unit_type": "lesson",
            "books_sources": {"triola": ["Ch.3"], "scutchfield": ["Ch.13"], "donaldson": ["Ch.2"]},
        },
        {
            "unit_number": "M02-U04",
            "title_fr": "Quiz pratique : Données de santé",
            "title_en": "Practice Quiz: Health Data",
            "description_fr": "Testez votre compréhension des types de données et statistiques de base",
            "description_en": "Test your understanding of data types and basic statistics",
            "estimated_minutes": 25,
            "order_index": 4,
            "unit_type": "quiz",
            "books_sources": {"triola": ["Ch.1", "Ch.2", "Ch.3"], "scutchfield": ["Ch.13"]},
        },
        {
            "unit_number": "M02-U05",
            "title_fr": "Exercice pratique : Analyse données paludisme Niger 2023",
            "title_en": "Practical Exercise: Niger Malaria Data Analysis 2023",
            "description_fr": "Créer histogramme et boxplot, rédiger un rapport d'analyse",
            "description_en": "Create histogram and boxplot, write an analysis report",
            "estimated_minutes": 40,
            "order_index": 5,
            "unit_type": "case-study",
            "books_sources": {"triola": ["Ch.2", "Ch.3"]},
        },
    ],
    3: [
        {
            "unit_number": "M03-U01",
            "title_fr": "Les 6 piliers OMS des systèmes de santé",
            "title_en": "WHO 6 building blocks of health systems",
            "description_fr": "Gouvernance, financement, RH, médicaments, information sanitaire, prestation",
            "description_en": "Governance, financing, human resources, medicines, health information, service delivery",
            "estimated_minutes": 45,
            "order_index": 1,
            "unit_type": "lesson",
            "books_sources": {"donaldson": ["Ch.6"], "scutchfield": ["Ch.6", "Ch.7"]},
        },
        {
            "unit_number": "M03-U02",
            "title_fr": "Financement de la santé et couverture santé universelle",
            "title_en": "Health financing and universal health coverage",
            "description_fr": "Modèles de financement; CSU en AOF; NHIS Ghana, CMU Sénégal",
            "description_en": "Financing models; UHC in West Africa; Ghana NHIS, Senegal CMU",
            "estimated_minutes": 50,
            "order_index": 2,
            "unit_type": "lesson",
            "books_sources": {"donaldson": ["Ch.6"], "scutchfield": ["Ch.8", "Ch.28"]},
        },
        {
            "unit_number": "M03-U03",
            "title_fr": "Défis et innovations des systèmes de santé AOF",
            "title_en": "Challenges and innovations in West African health systems",
            "description_fr": "Défis actuels, secteur privé, rôle des ONG, indicateurs de performance JCI/WHO",
            "description_en": "Current challenges, private sector, NGO role, JCI/WHO performance indicators",
            "estimated_minutes": 40,
            "order_index": 3,
            "unit_type": "lesson",
            "books_sources": {"scutchfield": ["Ch.28"]},
        },
        {
            "unit_number": "M03-U04",
            "title_fr": "Quiz pratique : Systèmes de santé",
            "title_en": "Practice Quiz: Health Systems",
            "description_fr": "Testez votre compréhension des systèmes de santé en AOF",
            "description_en": "Test your understanding of health systems in West Africa",
            "estimated_minutes": 25,
            "order_index": 4,
            "unit_type": "quiz",
            "books_sources": {"donaldson": ["Ch.6"], "scutchfield": ["Ch.6", "Ch.7", "Ch.8", "Ch.28"]},
        },
        {
            "unit_number": "M03-U05",
            "title_fr": "Étude comparative : NHIS Ghana comme modèle CSU en AOF",
            "title_en": "Comparative Study: Ghana NHIS as UHC model in West Africa",
            "description_fr": "Analyse comparée des politiques de santé : Ghana, Sénégal, Nigeria, Mali",
            "description_en": "Comparative analysis of health policies: Ghana, Senegal, Nigeria, Mali",
            "estimated_minutes": 40,
            "order_index": 5,
            "unit_type": "case-study",
            "books_sources": {"donaldson": ["Ch.6"], "scutchfield": ["Ch.28"]},
        },
    ],
    4: [
        {
            "unit_number": "M04-U01",
            "title_fr": "Mesures de morbidité et mortalité",
            "title_en": "Measures of morbidity and mortality",
            "description_fr": "Incidence cumulée, taux d'incidence, prévalence; TMG, TMI, TMM, espérance de vie",
            "description_en": "Cumulative incidence, incidence rate, prevalence; CMR, IMR, MMR, life expectancy",
            "estimated_minutes": 55,
            "order_index": 1,
            "unit_type": "lesson",
            "books_sources": {"donaldson": ["Ch.2"], "scutchfield": ["Ch.11"]},
        },
        {
            "unit_number": "M04-U02",
            "title_fr": "Design des études épidémiologiques",
            "title_en": "Epidemiological study designs",
            "description_fr": "Études cohorte, cas-témoins, transversales; forces et limites; RR, OR, NNT",
            "description_en": "Cohort, case-control, cross-sectional studies; strengths/limits; RR, OR, NNT",
            "estimated_minutes": 55,
            "order_index": 2,
            "unit_type": "lesson",
            "books_sources": {"donaldson": ["Ch.2"], "scutchfield": ["Ch.13"]},
        },
        {
            "unit_number": "M04-U03",
            "title_fr": "DALY, biais et investigation d'épidémie",
            "title_en": "DALY, bias and outbreak investigation",
            "description_fr": "AVCI/DALY, biais, facteurs de confusion; étapes OMS investigation terrain",
            "description_en": "DALY, bias, confounding factors; WHO field investigation steps",
            "estimated_minutes": 50,
            "order_index": 3,
            "unit_type": "lesson",
            "books_sources": {"donaldson": ["Ch.2"]},
        },
        {
            "unit_number": "M04-U04",
            "title_fr": "Quiz pratique : Épidémiologie",
            "title_en": "Practice Quiz: Epidemiology",
            "description_fr": "Calculs d'incidence/prévalence, choix de design d'étude, interprétation RR/OR",
            "description_en": "Incidence/prevalence calculations, study design choice, RR/OR interpretation",
            "estimated_minutes": 25,
            "order_index": 4,
            "unit_type": "quiz",
            "books_sources": {"donaldson": ["Ch.2"], "scutchfield": ["Ch.11", "Ch.13"]},
        },
        {
            "unit_number": "M04-U05",
            "title_fr": "Simulation : Investigation épidémie choléra Niger",
            "title_en": "Simulation: Cholera Outbreak Investigation Niger",
            "description_fr": "Jouer le rôle d'épidémiologiste OMS; données réelles OCHA/WHO 2022",
            "description_en": "Play the role of WHO epidemiologist; real OCHA/WHO 2022 data",
            "estimated_minutes": 50,
            "order_index": 5,
            "unit_type": "case-study",
            "books_sources": {"donaldson": ["Ch.2"]},
        },
    ],
    5: [
        {
            "unit_number": "M05-U01",
            "title_fr": "Probabilités et taux en santé",
            "title_en": "Probabilities and health rates",
            "description_fr": "Théorème de Bayes, sensibilité/spécificité, VPP/VPN; taux mortalité/fécondité",
            "description_en": "Bayes theorem, sensitivity/specificity, PPV/NPV; mortality/fertility rates",
            "estimated_minutes": 55,
            "order_index": 1,
            "unit_type": "lesson",
            "books_sources": {"triola": ["Ch.4", "Ch.5"]},
        },
        {
            "unit_number": "M05-U02",
            "title_fr": "Distributions de probabilité et inférence",
            "title_en": "Probability distributions and inference",
            "description_fr": "Distribution normale, binomiale, Poisson; TLC; intervalles de confiance IC95%",
            "description_en": "Normal, binomial, Poisson distributions; CLT; 95% confidence intervals",
            "estimated_minutes": 55,
            "order_index": 2,
            "unit_type": "lesson",
            "books_sources": {"triola": ["Ch.5", "Ch.6", "Ch.7"]},
        },
        {
            "unit_number": "M05-U03",
            "title_fr": "Tests d'hypothèse et taille d'échantillon",
            "title_en": "Hypothesis testing and sample size",
            "description_fr": "H0/H1, erreur α/β, puissance; tests t, z, chi-carré; taille d'échantillon",
            "description_en": "H0/H1, α/β error, power; t, z, chi-square tests; sample size calculation",
            "estimated_minutes": 55,
            "order_index": 3,
            "unit_type": "lesson",
            "books_sources": {"triola": ["Ch.8", "Ch.9"]},
        },
        {
            "unit_number": "M05-U04",
            "title_fr": "Quiz pratique : Biostatistiques",
            "title_en": "Practice Quiz: Biostatistics",
            "description_fr": "Calculs de probabilités, IC, tests d'hypothèse appliqués à la santé",
            "description_en": "Probability calculations, CI, hypothesis testing applied to health",
            "estimated_minutes": 25,
            "order_index": 4,
            "unit_type": "quiz",
            "books_sources": {"triola": ["Ch.4", "Ch.5", "Ch.6", "Ch.7", "Ch.8", "Ch.9"]},
        },
        {
            "unit_number": "M05-U05",
            "title_fr": "Exercice pratique : Prévalence anémie Mali (données DHS)",
            "title_en": "Practical Exercise: Anemia Prevalence Mali (DHS data)",
            "description_fr": "Estimer prévalence anémie femmes enceintes au Mali; calculer IC95%",
            "description_en": "Estimate anemia prevalence in pregnant women in Mali; calculate 95% CI",
            "estimated_minutes": 45,
            "order_index": 5,
            "unit_type": "case-study",
            "books_sources": {"triola": ["Ch.7", "Ch.8"]},
        },
    ],
    6: [
        {
            "unit_number": "M06-U01",
            "title_fr": "Double fardeau des maladies en Afrique de l'Ouest",
            "title_en": "Double burden of disease in West Africa",
            "description_fr": "Maladies transmissibles + MNT; profil épidémiologique comparé CEDEAO",
            "description_en": "Communicable + non-communicable diseases; comparative ECOWAS profile",
            "estimated_minutes": 50,
            "order_index": 1,
            "unit_type": "lesson",
            "books_sources": {"donaldson": ["Ch.3", "Ch.4"], "scutchfield": ["Ch.17", "Ch.22"]},
        },
        {
            "unit_number": "M06-U02",
            "title_fr": "Paludisme, VIH/SIDA et tuberculose en AOF",
            "title_en": "Malaria, HIV/AIDS and tuberculosis in West Africa",
            "description_fr": "Épidémiologie, prévention, traitement; objectifs 95-95-95 VIH; TB-VIH",
            "description_en": "Epidemiology, prevention, treatment; HIV 95-95-95 targets; TB-HIV coinfection",
            "estimated_minutes": 55,
            "order_index": 2,
            "unit_type": "lesson",
            "books_sources": {"donaldson": ["Ch.3"], "scutchfield": ["Ch.22"]},
        },
        {
            "unit_number": "M06-U03",
            "title_fr": "MNT émergentes et déterminants sociaux en AOF",
            "title_en": "Emerging NCDs and social determinants in West Africa",
            "description_fr": "HTA, diabète, cancers; nutrition/sécurité alimentaire; déterminants sociaux",
            "description_en": "Hypertension, diabetes, cancers; nutrition/food security; social determinants",
            "estimated_minutes": 50,
            "order_index": 3,
            "unit_type": "lesson",
            "books_sources": {"donaldson": ["Ch.4", "Ch.5"], "scutchfield": ["Ch.18", "Ch.25"]},
        },
        {
            "unit_number": "M06-U04",
            "title_fr": "Quiz pratique : Maladies et déterminants",
            "title_en": "Practice Quiz: Diseases and determinants",
            "description_fr": "Testez votre connaissance du profil épidémiologique AOF",
            "description_en": "Test your knowledge of the West African epidemiological profile",
            "estimated_minutes": 25,
            "order_index": 4,
            "unit_type": "quiz",
            "books_sources": {"donaldson": ["Ch.3", "Ch.4", "Ch.5"], "scutchfield": ["Ch.17", "Ch.18", "Ch.22", "Ch.25"]},
        },
        {
            "unit_number": "M06-U05",
            "title_fr": "Analyse comparative : Charge paludisme Nigeria vs Sénégal",
            "title_en": "Comparative Analysis: Malaria Burden Nigeria vs Senegal",
            "description_fr": "Analyser les indicateurs WHO AFRO 2023; facteurs de succès Sénégal",
            "description_en": "Analyze WHO AFRO 2023 indicators; success factors in Senegal",
            "estimated_minutes": 40,
            "order_index": 5,
            "unit_type": "case-study",
            "books_sources": {"donaldson": ["Ch.3"]},
        },
    ],
    7: [
        {
            "unit_number": "M07-U01",
            "title_fr": "Leadership en santé publique",
            "title_en": "Leadership in public health",
            "description_fr": "Modèles de leadership Kouzes-Posner, situationnel; gestion d'équipe ressources-limitées",
            "description_en": "Kouzes-Posner, situational leadership models; managing teams in resource-limited settings",
            "estimated_minutes": 45,
            "order_index": 1,
            "unit_type": "lesson",
            "books_sources": {"scutchfield": ["Ch.9", "Ch.10"]},
        },
        {
            "unit_number": "M07-U02",
            "title_fr": "Évaluation communautaire et planification sanitaire",
            "title_en": "Community assessment and health planning",
            "description_fr": "MAPP, PATCH; objectifs SMART; plan de santé communautaire",
            "description_en": "MAPP, PATCH frameworks; SMART objectives; community health planning",
            "estimated_minutes": 50,
            "order_index": 2,
            "unit_type": "lesson",
            "books_sources": {"scutchfield": ["Ch.11", "Ch.12"]},
        },
        {
            "unit_number": "M07-U03",
            "title_fr": "Performance, données de santé et comportement",
            "title_en": "Performance, health data and behavior",
            "description_fr": "KPI santé publique; gestion des données; théories HBM, TTM, TPS",
            "description_en": "Public health KPIs; data management; HBM, TTM, TPS behavioral theories",
            "estimated_minutes": 50,
            "order_index": 3,
            "unit_type": "lesson",
            "books_sources": {"scutchfield": ["Ch.14", "Ch.15", "Ch.16"]},
        },
        {
            "unit_number": "M07-U04",
            "title_fr": "Quiz pratique : Outils de santé publique",
            "title_en": "Practice Quiz: Public health tools",
            "description_fr": "Testez vos connaissances en leadership, planification et gestion des données",
            "description_en": "Test your knowledge of leadership, planning and data management",
            "estimated_minutes": 25,
            "order_index": 4,
            "unit_type": "quiz",
            "books_sources": {"scutchfield": ["Ch.9", "Ch.10", "Ch.11", "Ch.12", "Ch.14", "Ch.15", "Ch.16"]},
        },
        {
            "unit_number": "M07-U05",
            "title_fr": "Planification : Programme de santé district rural Burkina Faso",
            "title_en": "Planning: Rural district health program Burkina Faso",
            "description_fr": "Élaborer un plan de santé communautaire avec données DHIS2 réelles",
            "description_en": "Develop a community health plan with real DHIS2 data",
            "estimated_minutes": 50,
            "order_index": 5,
            "unit_type": "case-study",
            "books_sources": {"scutchfield": ["Ch.11", "Ch.12"]},
        },
    ],
    8: [
        {
            "unit_number": "M08-U01",
            "title_fr": "Types de surveillance et systèmes IDSR",
            "title_en": "Surveillance types and IDSR systems",
            "description_fr": "Surveillance passive, active, sentinelle, syndromique; IDSR AOF",
            "description_en": "Passive, active, sentinel, syndromic surveillance; IDSR West Africa",
            "estimated_minutes": 50,
            "order_index": 1,
            "unit_type": "lesson",
            "books_sources": {"donaldson": ["Ch.2", "Ch.3"], "scutchfield": ["Ch.13"]},
        },
        {
            "unit_number": "M08-U02",
            "title_fr": "DHIS2 pour la surveillance des maladies",
            "title_en": "DHIS2 for disease surveillance",
            "description_fr": "Architecture DHIS2, saisie, agrégation, visualisation, tableaux de bord",
            "description_en": "DHIS2 architecture, data entry, aggregation, visualization, dashboards",
            "estimated_minutes": 55,
            "order_index": 2,
            "unit_type": "lesson",
            "books_sources": {"scutchfield": ["Ch.13"]},
        },
        {
            "unit_number": "M08-U03",
            "title_fr": "Go.Data, SORMAS et RSI pour les urgences sanitaires",
            "title_en": "Go.Data, SORMAS and IHR for health emergencies",
            "description_fr": "Outils numériques gestion épidémies; RSI 2005; capacités IHR en AOF",
            "description_en": "Digital outbreak management tools; IHR 2005; IHR capacities in West Africa",
            "estimated_minutes": 50,
            "order_index": 3,
            "unit_type": "lesson",
            "books_sources": {"donaldson": ["Ch.3"]},
        },
        {
            "unit_number": "M08-U04",
            "title_fr": "Quiz pratique : Surveillance numérique",
            "title_en": "Practice Quiz: Digital surveillance",
            "description_fr": "Testez votre compréhension des systèmes de surveillance en AOF",
            "description_en": "Test your understanding of surveillance systems in West Africa",
            "estimated_minutes": 25,
            "order_index": 4,
            "unit_type": "quiz",
            "books_sources": {"donaldson": ["Ch.2", "Ch.3"], "scutchfield": ["Ch.13"]},
        },
        {
            "unit_number": "M08-U05",
            "title_fr": "TP : Tableau de bord DHIS2 surveillance méningite Niger",
            "title_en": "Lab: DHIS2 surveillance dashboard for meningitis Niger",
            "description_fr": "Configurer un tableau de bord DHIS2 fictif; analyser une flambée simulée",
            "description_en": "Configure a fictional DHIS2 dashboard; analyze a simulated outbreak",
            "estimated_minutes": 55,
            "order_index": 5,
            "unit_type": "case-study",
            "books_sources": {"scutchfield": ["Ch.13"]},
        },
    ],
    9: [
        {
            "unit_number": "M09-U01",
            "title_fr": "Corrélation, régression linéaire et logistique",
            "title_en": "Correlation, linear and logistic regression",
            "description_fr": "Pearson/Spearman, régression linéaire simple/multiple, régression logistique",
            "description_en": "Pearson/Spearman, simple/multiple linear regression, logistic regression",
            "estimated_minutes": 60,
            "order_index": 1,
            "unit_type": "lesson",
            "books_sources": {"triola": ["Ch.10"]},
        },
        {
            "unit_number": "M09-U02",
            "title_fr": "ANOVA et tests non-paramétriques",
            "title_en": "ANOVA and non-parametric tests",
            "description_fr": "ANOVA à 1 facteur, Tukey post-hoc; Wilcoxon, Mann-Whitney, Kruskal-Wallis",
            "description_en": "One-way ANOVA, Tukey post-hoc; Wilcoxon, Mann-Whitney, Kruskal-Wallis",
            "estimated_minutes": 55,
            "order_index": 2,
            "unit_type": "lesson",
            "books_sources": {"triola": ["Ch.11", "Ch.12", "Ch.13"]},
        },
        {
            "unit_number": "M09-U03",
            "title_fr": "Analyse de survie Kaplan-Meier et R/Python",
            "title_en": "Kaplan-Meier survival analysis and R/Python",
            "description_fr": "Tables de vie, Kaplan-Meier, log-rank test, Cox; introduction R/Python/STATA",
            "description_en": "Life tables, Kaplan-Meier, log-rank test, Cox model; intro R/Python/STATA",
            "estimated_minutes": 60,
            "order_index": 3,
            "unit_type": "lesson",
            "books_sources": {"triola": ["Ch.14"]},
        },
        {
            "unit_number": "M09-U04",
            "title_fr": "Quiz pratique : Statistiques avancées",
            "title_en": "Practice Quiz: Advanced statistics",
            "description_fr": "Régression, ANOVA, tests non-paramétriques et analyse de survie",
            "description_en": "Regression, ANOVA, non-parametric tests and survival analysis",
            "estimated_minutes": 25,
            "order_index": 4,
            "unit_type": "quiz",
            "books_sources": {"triola": ["Ch.10", "Ch.11", "Ch.12", "Ch.13", "Ch.14"]},
        },
        {
            "unit_number": "M09-U05",
            "title_fr": "Projet : Déterminants mortalité infantile Sénégal (DHS 2019)",
            "title_en": "Project: Infant mortality determinants Senegal (DHS 2019 data)",
            "description_fr": "Régression logistique, ANOVA comparaison vaccination 5 pays, Kaplan-Meier VIH Ghana",
            "description_en": "Logistic regression, ANOVA vaccination comparison 5 countries, Kaplan-Meier HIV Ghana",
            "estimated_minutes": 60,
            "order_index": 5,
            "unit_type": "case-study",
            "books_sources": {"triola": ["Ch.10", "Ch.14"]},
        },
    ],
    10: [
        {
            "unit_number": "M10-U01",
            "title_fr": "Composantes d'un HMIS et DHIS2 avancé",
            "title_en": "HMIS components and advanced DHIS2",
            "description_fr": "Architecture HMIS; configurer DHIS2 pour collecte et analyse de données de santé",
            "description_en": "HMIS architecture; configure DHIS2 for health data collection and analysis",
            "estimated_minutes": 55,
            "order_index": 1,
            "unit_type": "lesson",
            "books_sources": {"scutchfield": ["Ch.13"]},
        },
        {
            "unit_number": "M10-U02",
            "title_fr": "Standards d'interopérabilité et mHealth en AOF",
            "title_en": "Interoperability standards and mHealth in West Africa",
            "description_fr": "HL7 FHIR, OpenHIE, OpenMRS, ODK; applications mHealth et impact AOF",
            "description_en": "HL7 FHIR, OpenHIE, OpenMRS, ODK; mHealth applications and impact in West Africa",
            "estimated_minutes": 50,
            "order_index": 2,
            "unit_type": "lesson",
            "books_sources": {"scutchfield": ["Ch.13"]},
        },
        {
            "unit_number": "M10-U03",
            "title_fr": "IA en santé, qualité des données et éthique",
            "title_en": "AI in health, data quality and ethics",
            "description_fr": "Opportunités/risques IA pour la santé AOF; qualité, confidentialité, éthique",
            "description_en": "AI opportunities/risks for West African health; quality, privacy, ethics",
            "estimated_minutes": 45,
            "order_index": 3,
            "unit_type": "lesson",
            "books_sources": {"scutchfield": ["Ch.13"]},
        },
        {
            "unit_number": "M10-U04",
            "title_fr": "Quiz pratique : Santé numérique",
            "title_en": "Practice Quiz: Digital health",
            "description_fr": "Testez vos connaissances HMIS, mHealth et interopérabilité",
            "description_en": "Test your knowledge of HMIS, mHealth and interoperability",
            "estimated_minutes": 25,
            "order_index": 4,
            "unit_type": "quiz",
            "books_sources": {"scutchfield": ["Ch.13"]},
        },
        {
            "unit_number": "M10-U05",
            "title_fr": "Étude de cas : Programme mHealth iCCM au Ghana",
            "title_en": "Case Study: iCCM mHealth programme in Ghana",
            "description_fr": "Évaluation qualité données DHIS2 Bénin; projets IA santé AOF",
            "description_en": "Evaluation of DHIS2 data quality in Benin; AI health projects in West Africa",
            "estimated_minutes": 45,
            "order_index": 5,
            "unit_type": "case-study",
            "books_sources": {"scutchfield": ["Ch.13"]},
        },
    ],
    11: [
        {
            "unit_number": "M11-U01",
            "title_fr": "Changement climatique et santé en AOF",
            "title_en": "Climate change and health in West Africa",
            "description_fr": "Impacts climatiques sur la santé; WASH; inondations Sahel 2024",
            "description_en": "Climate health impacts; WASH; Sahel 2024 floods",
            "estimated_minutes": 50,
            "order_index": 1,
            "unit_type": "lesson",
            "books_sources": {"donaldson": ["Ch.12"], "scutchfield": ["Ch.23"]},
        },
        {
            "unit_number": "M11-U02",
            "title_fr": "One Health et zoonoses en Afrique de l'Ouest",
            "title_en": "One Health and zoonoses in West Africa",
            "description_fr": "Concept One Health; zoonoses prioritaires AOF; Initiative One Health CEDEAO",
            "description_en": "One Health concept; priority zoonoses in West Africa; ECOWAS One Health Initiative",
            "estimated_minutes": 45,
            "order_index": 2,
            "unit_type": "lesson",
            "books_sources": {"donaldson": ["Ch.12"]},
        },
        {
            "unit_number": "M11-U03",
            "title_fr": "Pollution, évaluation d'impact et WASH",
            "title_en": "Pollution, impact assessment and WASH",
            "description_fr": "Qualité de l'air Dakar/Lagos; EIS/HIA; eau potable et assainissement AOF",
            "description_en": "Air quality Dakar/Lagos; HIA methodology; drinking water and sanitation in West Africa",
            "estimated_minutes": 40,
            "order_index": 3,
            "unit_type": "lesson",
            "books_sources": {"donaldson": ["Ch.12"], "scutchfield": ["Ch.23"]},
        },
        {
            "unit_number": "M11-U04",
            "title_fr": "Quiz pratique : Santé environnementale",
            "title_en": "Practice Quiz: Environmental health",
            "description_fr": "Testez vos connaissances sur le changement climatique, One Health et WASH",
            "description_en": "Test your knowledge of climate change, One Health and WASH",
            "estimated_minutes": 25,
            "order_index": 4,
            "unit_type": "quiz",
            "books_sources": {"donaldson": ["Ch.12"], "scutchfield": ["Ch.23"]},
        },
        {
            "unit_number": "M11-U05",
            "title_fr": "Étude de cas : Impacts sanitaires des inondations Sahel 2024",
            "title_en": "Case Study: Health impacts of Sahel 2024 floods",
            "description_fr": "Analyser les impacts Niger, Tchad, Sénégal; données AirQo Dakar",
            "description_en": "Analyze impacts in Niger, Chad, Senegal; AirQo Dakar air quality data",
            "estimated_minutes": 40,
            "order_index": 5,
            "unit_type": "case-study",
            "books_sources": {"donaldson": ["Ch.12"]},
        },
    ],
    12: [
        {
            "unit_number": "M12-U01",
            "title_fr": "Continuum de soins SMNI et mortalité maternelle",
            "title_en": "MNCH care continuum and maternal mortality",
            "description_fr": "Soins grossesse/accouchement/post-partum; les 3 retards Thaddeus & Maine",
            "description_en": "Pregnancy/childbirth/postpartum care; 3 delays by Thaddeus & Maine; MMR West Africa",
            "estimated_minutes": 55,
            "order_index": 1,
            "unit_type": "lesson",
            "books_sources": {"donaldson": ["Ch.8"], "scutchfield": ["Ch.25"]},
        },
        {
            "unit_number": "M12-U02",
            "title_fr": "PTME, nutrition infantile et vaccination",
            "title_en": "PMTCT, child nutrition and vaccination",
            "description_fr": "Protocoles PTME; allaitement, ANJE, MAS; PEV/EPI, couverture vaccination",
            "description_en": "PMTCT protocols; breastfeeding, IYCF, SAM; EPI immunization coverage",
            "estimated_minutes": 55,
            "order_index": 2,
            "unit_type": "lesson",
            "books_sources": {"donaldson": ["Ch.8"], "scutchfield": ["Ch.25"]},
        },
        {
            "unit_number": "M12-U03",
            "title_fr": "Agents de santé communautaires et modèles iCCM",
            "title_en": "Community health workers and iCCM models",
            "description_fr": "Modèles ASC/CHW en AOF; CHPS Ghana; suivi indicateurs SMNI avec DHIS2",
            "description_en": "CHW models in West Africa; Ghana CHPS; tracking MNCH indicators with DHIS2",
            "estimated_minutes": 45,
            "order_index": 3,
            "unit_type": "lesson",
            "books_sources": {"scutchfield": ["Ch.25"]},
        },
        {
            "unit_number": "M12-U04",
            "title_fr": "Quiz pratique : Santé maternelle et infantile",
            "title_en": "Practice Quiz: Maternal and child health",
            "description_fr": "Testez vos connaissances SMNI, PTME, nutrition et vaccination",
            "description_en": "Test your knowledge of MNCH, PMTCT, nutrition and vaccination",
            "estimated_minutes": 25,
            "order_index": 4,
            "unit_type": "quiz",
            "books_sources": {"donaldson": ["Ch.8"], "scutchfield": ["Ch.25"]},
        },
        {
            "unit_number": "M12-U05",
            "title_fr": "Analyse : Programme vaccination Sénégal — succès et leçons",
            "title_en": "Analysis: Senegal vaccination programme — successes and lessons",
            "description_fr": "Couverture rougeole >95%; modèle ASC communautaires Ghana CHPS",
            "description_en": "Measles coverage >95%; Ghana CHPS community health worker model",
            "estimated_minutes": 40,
            "order_index": 5,
            "unit_type": "case-study",
            "books_sources": {"donaldson": ["Ch.8"]},
        },
    ],
    13: [
        {
            "unit_number": "M13-U01",
            "title_fr": "Cycle des politiques de santé et acteurs d'influence",
            "title_en": "Health policy cycle and influencing actors",
            "description_fr": "Analyse des politiques; stakeholders, force field, SWOT; gouvernance multiniveaux",
            "description_en": "Policy analysis; stakeholders, force field, SWOT; multi-level governance",
            "estimated_minutes": 55,
            "order_index": 1,
            "unit_type": "lesson",
            "books_sources": {"scutchfield": ["Ch.9", "Ch.16"], "donaldson": ["Ch.6", "Ch.7"]},
        },
        {
            "unit_number": "M13-U02",
            "title_fr": "Plaidoyer structuré et partenariats multi-acteurs",
            "title_en": "Structured advocacy and multi-stakeholder partnerships",
            "description_fr": "Élaborer un plaidoyer pour une politique de santé; gérer partenariats ONG/privé",
            "description_en": "Develop health policy advocacy; manage NGO/private sector partnerships",
            "estimated_minutes": 50,
            "order_index": 2,
            "unit_type": "lesson",
            "books_sources": {"scutchfield": ["Ch.19", "Ch.29"]},
        },
        {
            "unit_number": "M13-U03",
            "title_fr": "Évaluation des politiques de santé",
            "title_en": "Health policy evaluation",
            "description_fr": "Efficacité, équité, efficience; outils d'évaluation; qualité des soins",
            "description_en": "Effectiveness, equity, efficiency; evaluation tools; quality of care",
            "estimated_minutes": 45,
            "order_index": 3,
            "unit_type": "lesson",
            "books_sources": {"donaldson": ["Ch.7"], "scutchfield": ["Ch.16"]},
        },
        {
            "unit_number": "M13-U04",
            "title_fr": "Quiz pratique : Leadership et politique",
            "title_en": "Practice Quiz: Leadership and policy",
            "description_fr": "Testez vos connaissances en gouvernance sanitaire et plaidoyer",
            "description_en": "Test your knowledge of health governance and advocacy",
            "estimated_minutes": 25,
            "order_index": 4,
            "unit_type": "quiz",
            "books_sources": {"scutchfield": ["Ch.9", "Ch.16", "Ch.19", "Ch.29"], "donaldson": ["Ch.6", "Ch.7"]},
        },
        {
            "unit_number": "M13-U05",
            "title_fr": "Simulation : Plaidoyer financement santé devant ministre Niger",
            "title_en": "Simulation: Health financing advocacy before Niger minister",
            "description_fr": "Défendre une politique de financement basée sur l'impôt; analyse CSU AOF",
            "description_en": "Defend a tax-based health financing policy; analysis of UHC progress in West Africa",
            "estimated_minutes": 50,
            "order_index": 5,
            "unit_type": "case-study",
            "books_sources": {"scutchfield": ["Ch.9"]},
        },
    ],
    14: [
        {
            "unit_number": "M14-U01",
            "title_fr": "Formulation de questions de recherche et protocoles",
            "title_en": "Research question formulation and protocols",
            "description_fr": "PICO/PECO; conception d'études opérationnelles; essais cliniques, quasi-expérimentaux",
            "description_en": "PICO/PECO; operational research design; clinical trials, quasi-experimental",
            "estimated_minutes": 55,
            "order_index": 1,
            "unit_type": "lesson",
            "books_sources": {"triola": ["Ch.7", "Ch.8"], "scutchfield": ["Ch.12"]},
        },
        {
            "unit_number": "M14-U02",
            "title_fr": "Revue systématique, méta-analyse et évaluation de programme",
            "title_en": "Systematic review, meta-analysis and programme evaluation",
            "description_fr": "PRISMA, PubMed, Cochrane; forest plot, hétérogénéité; RE-AIM, CIPP",
            "description_en": "PRISMA, PubMed, Cochrane; forest plot, heterogeneity; RE-AIM, CIPP frameworks",
            "estimated_minutes": 55,
            "order_index": 2,
            "unit_type": "lesson",
            "books_sources": {"triola": ["Ch.9", "Ch.10"], "scutchfield": ["Ch.17"]},
        },
        {
            "unit_number": "M14-U03",
            "title_fr": "Analyse économique, éthique et rédaction scientifique",
            "title_en": "Economic analysis, ethics and scientific writing",
            "description_fr": "Coût-efficacité, AVCI, seuil décision; éthique CAMES; format IMRAD",
            "description_en": "Cost-effectiveness, DALY, decision threshold; CAMES ethics; IMRAD format",
            "estimated_minutes": 50,
            "order_index": 3,
            "unit_type": "lesson",
            "books_sources": {"triola": ["Ch.14"], "scutchfield": ["Ch.17"]},
        },
        {
            "unit_number": "M14-U04",
            "title_fr": "Quiz pratique : Recherche et évaluation",
            "title_en": "Practice Quiz: Research and evaluation",
            "description_fr": "Testez vos connaissances en méthodologie de recherche et évaluation",
            "description_en": "Test your knowledge of research methodology and evaluation",
            "estimated_minutes": 25,
            "order_index": 4,
            "unit_type": "quiz",
            "books_sources": {"triola": ["Ch.7", "Ch.8", "Ch.9", "Ch.10", "Ch.14"], "scutchfield": ["Ch.12", "Ch.17"]},
        },
        {
            "unit_number": "M14-U05",
            "title_fr": "Projet : Évaluation impact programme moustiquaires Nord Nigeria",
            "title_en": "Project: Evaluation of bed net programme impact North Nigeria",
            "description_fr": "Design quasi-expérimental différence-en-différences; analyse DHIS2; rédaction article",
            "description_en": "Difference-in-differences quasi-experimental design; DHIS2 analysis; article writing",
            "estimated_minutes": 60,
            "order_index": 5,
            "unit_type": "case-study",
            "books_sources": {"triola": ["Ch.7", "Ch.8"]},
        },
    ],
    15: [
        {
            "unit_number": "M15-U01",
            "title_fr": "Analyse de situation épidémiologique et déterminants",
            "title_en": "Epidemiological situation analysis and determinants",
            "description_fr": "Analyser la situation d'un district AOF réel avec données DHIS2/DHS",
            "description_en": "Analyze the situation of a real AOF district with DHIS2/DHS data",
            "estimated_minutes": 60,
            "order_index": 1,
            "unit_type": "lesson",
            "books_sources": {"donaldson": ["Ch.1", "Ch.2"], "triola": ["Ch.1"], "scutchfield": ["Ch.1"]},
        },
        {
            "unit_number": "M15-U02",
            "title_fr": "Analyse statistique et revue de littérature",
            "title_en": "Statistical analysis and literature review",
            "description_fr": "Appliquer les méthodes statistiques; revue de littérature des interventions efficaces",
            "description_en": "Apply statistical methods; literature review of effective interventions",
            "estimated_minutes": 60,
            "order_index": 2,
            "unit_type": "lesson",
            "books_sources": {"triola": ["Ch.10", "Ch.14"]},
        },
        {
            "unit_number": "M15-U03",
            "title_fr": "Plan d'intervention et tableau de bord DHIS2",
            "title_en": "Intervention plan and DHIS2 dashboard",
            "description_fr": "Stratégie d'intervention basée sur les données; tableau de bord DHIS2",
            "description_en": "Evidence-based intervention strategy; DHIS2 monitoring dashboard",
            "estimated_minutes": 60,
            "order_index": 3,
            "unit_type": "lesson",
            "books_sources": {"scutchfield": ["Ch.11", "Ch.12", "Ch.13"]},
        },
        {
            "unit_number": "M15-U04",
            "title_fr": "Faisabilité, analyse économique et brief politique",
            "title_en": "Feasibility, economic analysis and policy brief",
            "description_fr": "Analyse de faisabilité; analyse économique; brief politique (2 pages)",
            "description_en": "Feasibility analysis; economic analysis; 2-page policy brief",
            "estimated_minutes": 55,
            "order_index": 4,
            "unit_type": "lesson",
            "books_sources": {"scutchfield": ["Ch.17"], "triola": ["Ch.14"]},
        },
        {
            "unit_number": "M15-U05",
            "title_fr": "Projet Capstone Final : Présentation et défense",
            "title_en": "Final Capstone Project: Presentation and defense",
            "description_fr": "Présenter les recommandations sous forme de brief politique et présentation orale",
            "description_en": "Present recommendations as policy brief and oral presentation",
            "estimated_minutes": 90,
            "order_index": 5,
            "unit_type": "case-study",
            "books_sources": {
                "donaldson": ["Ch.1", "Ch.2", "Ch.3", "Ch.4", "Ch.5", "Ch.6", "Ch.7", "Ch.8", "Ch.12", "Ch.13"],
                "scutchfield": ["Ch.1", "Ch.9", "Ch.11", "Ch.13", "Ch.17"],
                "triola": ["Ch.1", "Ch.10", "Ch.14"],
            },
        },
    ],
}


async def seed_units(session: AsyncSession) -> None:
    created = 0
    updated = 0

    for module_number, units in SYLLABUS_UNITS.items():
        result = await session.execute(
            select(Module).where(Module.module_number == module_number)
        )
        module = result.scalar_one_or_none()
        if not module:
            logger.warning("Module not found, skipping", module_number=module_number)
            continue

        for unit_data in units:
            existing = await session.execute(
                select(ModuleUnit).where(
                    ModuleUnit.module_id == module.id,
                    ModuleUnit.unit_number == unit_data["unit_number"],
                )
            )
            unit = existing.scalar_one_or_none()

            if unit:
                unit.title_fr = unit_data["title_fr"]
                unit.title_en = unit_data["title_en"]
                unit.description_fr = unit_data.get("description_fr")
                unit.description_en = unit_data.get("description_en")
                unit.estimated_minutes = unit_data["estimated_minutes"]
                unit.order_index = unit_data["order_index"]
                unit.unit_type = unit_data["unit_type"]
                unit.books_sources = unit_data.get("books_sources")
                updated += 1
            else:
                new_unit = ModuleUnit(
                    module_id=module.id,
                    unit_number=unit_data["unit_number"],
                    title_fr=unit_data["title_fr"],
                    title_en=unit_data["title_en"],
                    description_fr=unit_data.get("description_fr"),
                    description_en=unit_data.get("description_en"),
                    estimated_minutes=unit_data["estimated_minutes"],
                    order_index=unit_data["order_index"],
                    unit_type=unit_data["unit_type"],
                    books_sources=unit_data.get("books_sources"),
                )
                session.add(new_unit)
                created += 1

    await session.commit()
    logger.info("Seeding complete", created=created, updated=updated)


async def main() -> None:
    settings = get_settings()
    engine = create_async_engine(settings.database_url, echo=False)
    async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    async with async_session() as session:
        await seed_units(session)

    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(main())
