"""Course creation agent service — generates full course structure using Claude API."""

import json

import structlog
from anthropic import AsyncAnthropic

from app.infrastructure.config.settings import settings

logger = structlog.get_logger(__name__)

COURSE_STRUCTURE_PROMPT = """Tu es un expert en conception pédagogique pour la santé publique en Afrique de l'Ouest.

Tu dois générer une structure de cours complète basée sur les informations fournies.
La structure doit suivre les principes pédagogiques de Bloom et être adaptée au contexte africain.

Génère la réponse UNIQUEMENT en JSON valide avec la structure suivante:
{
  "modules": [
    {
      "module_number": 1,
      "level": 1,
      "title_fr": "...",
      "title_en": "...",
      "description_fr": "...",
      "description_en": "...",
      "estimated_hours": 20,
      "bloom_level": "remember|understand|apply|analyze|evaluate|create",
      "learning_objectives_fr": ["...", "..."],
      "learning_objectives_en": ["...", "..."],
      "key_topics": ["...", "..."]
    }
  ]
}

Respecte ces contraintes:
- 3 à 10 modules par cours
- Progression pédagogique cohérente (du simple au complexe)
- Niveaux Bloom croissants
- Contenu contextualisé pour l'Afrique de l'Ouest
- Bilingue FR/EN obligatoire
"""


class CourseAgentService:
    """Generates full course structure using Claude API."""

    def __init__(self) -> None:
        self._client: AsyncAnthropic | None = None

    def _get_client(self) -> AsyncAnthropic | None:
        if not settings.anthropic_api_key:
            return None
        if self._client is None:
            self._client = AsyncAnthropic(api_key=settings.anthropic_api_key)
        return self._client

    async def generate_course_structure(
        self,
        title_fr: str,
        title_en: str,
        domain: str,
        target_audience: str,
        description_fr: str | None = None,
        description_en: str | None = None,
    ) -> list[dict]:
        """
        Generate full course module structure using Claude API.

        Returns list of module dicts. Falls back to placeholder on error or missing API key.
        """
        client = self._get_client()
        if not client:
            logger.warning("Anthropic API key not set — using placeholder course structure")
            return self._placeholder_structure(title_fr, title_en)

        user_message = f"""Génère la structure d'un cours avec ces informations:

Titre (FR): {title_fr}
Titre (EN): {title_en}
Domaine: {domain}
Public cible: {target_audience}
Description (FR): {description_fr or "Non fournie"}
Description (EN): {description_en or "Not provided"}

Génère entre 4 et 8 modules progressifs adaptés à ce domaine."""

        try:
            response = await client.messages.create(
                model="claude-sonnet-4-6",
                max_tokens=4096,
                system=COURSE_STRUCTURE_PROMPT,
                messages=[{"role": "user", "content": user_message}],
            )

            content_text = response.content[0].text if response.content else ""
            json_start = content_text.find("{")
            json_end = content_text.rfind("}") + 1
            if json_start == -1 or json_end == 0:
                logger.error("No JSON found in agent response")
                return self._placeholder_structure(title_fr, title_en)

            parsed = json.loads(content_text[json_start:json_end])
            modules = parsed.get("modules", [])

            logger.info(
                "Course structure generated by agent",
                title_fr=title_fr,
                module_count=len(modules),
            )
            return modules

        except Exception as e:
            logger.error("Course agent generation failed", error=str(e))
            return self._placeholder_structure(title_fr, title_en)

    def _placeholder_structure(self, title_fr: str, title_en: str) -> list[dict]:
        """Return a minimal placeholder structure when agent is unavailable."""
        return [
            {
                "module_number": 1,
                "level": 1,
                "title_fr": f"Introduction à {title_fr}",
                "title_en": f"Introduction to {title_en}",
                "description_fr": "Module d'introduction aux concepts fondamentaux.",
                "description_en": "Introductory module covering fundamental concepts.",
                "estimated_hours": 20,
                "bloom_level": "remember",
                "learning_objectives_fr": ["Comprendre les concepts de base"],
                "learning_objectives_en": ["Understand basic concepts"],
                "key_topics": ["Introduction", "Fondamentaux"],
            },
            {
                "module_number": 2,
                "level": 2,
                "title_fr": f"Pratiques de {title_fr}",
                "title_en": f"Practices of {title_en}",
                "description_fr": "Application des concepts fondamentaux.",
                "description_en": "Application of fundamental concepts.",
                "estimated_hours": 25,
                "bloom_level": "apply",
                "learning_objectives_fr": ["Appliquer les méthodes apprises"],
                "learning_objectives_en": ["Apply learned methods"],
                "key_topics": ["Méthodes", "Applications"],
            },
        ]
