-- Supabase project configuration for SantePublique AOF
-- This file documents the required Supabase project setup

-- =============================================================================
-- 1. PROJECT SETUP
-- =============================================================================

-- Project Name: santepublique-aof
-- Region: us-east-1 (or eu-west-1 for GDPR compliance)
-- PostgreSQL Version: 16
-- Organization: santepublique-aof

-- =============================================================================
-- 2. AUTHENTICATION SETTINGS
-- =============================================================================

-- Navigate to Authentication > Settings in Supabase Dashboard

-- Site URL: https://your-production-domain.com (or localhost:3000 for dev)
-- Additional Redirect URLs:
--   - http://localhost:3000/auth/callback
--   - https://staging.santepublique-aof.com/auth/callback
--   - https://app.santepublique-aof.com/auth/callback

-- Email Auth: Enable
-- Phone Auth: Disable (not needed for this project)
-- Confirm email: Enable
-- Email template customization: Enable (French + English templates)

-- Password policy:
-- Minimum password length: 8
-- Require uppercase: true
-- Require lowercase: true 
-- Require numbers: true
-- Require symbols: false

-- =============================================================================
-- 3. OAUTH PROVIDERS CONFIGURATION
-- =============================================================================

-- Google OAuth Provider
-- 1. Go to Google Cloud Console: https://console.cloud.google.com/
-- 2. Create new project: "santepublique-aof" 
-- 3. Enable Google+ API and OAuth consent screen
-- 4. Create OAuth 2.0 credentials (Web application)
-- 5. Add authorized redirect URIs:
--    - https://your-project-ref.supabase.co/auth/v1/callback
-- 6. Copy Client ID and Client Secret to Supabase Auth > Providers > Google

-- LinkedIn OAuth Provider  
-- 1. Go to LinkedIn Developers: https://www.linkedin.com/developers/
-- 2. Create new app: "SantePublique AOF Learning Platform"
-- 3. Add redirect URLs:
--    - https://your-project-ref.supabase.co/auth/v1/callback
-- 4. Request access to Sign In with LinkedIn using OpenID Connect
-- 5. Copy Client ID and Client Secret to Supabase Auth > Providers > LinkedIn

-- =============================================================================
-- 4. JWT SETTINGS  
-- =============================================================================

-- JWT expiry: 1 hour (3600 seconds)
-- JWT refresh expiry: 24 hours (86400 seconds)  
-- Enable automatic refresh token rotation: true
-- JWT secret: Auto-generated by Supabase (stored in SUPABASE_JWT_SECRET env var)

-- =============================================================================
-- 5. CUSTOM CLAIMS (for user context)
-- =============================================================================

-- Custom claims added to JWT payload:
-- {
--   "user_id": "uuid",
--   "email": "user@example.com", 
--   "preferred_language": "fr|en",
--   "country": "senegal|ghana|mali|...",
--   "current_level": 1-4,
--   "professional_role": "doctor|nurse|researcher|student|..."
-- }

-- =============================================================================
-- 6. WEBHOOKS (for profile sync)
-- =============================================================================

-- Add webhook to sync user profile data to our backend:
-- URL: https://your-backend-api.com/api/v1/auth/webhook/user-created
-- Events: user.created, user.updated
-- HTTP Headers: 
--   - Authorization: Bearer WEBHOOK_SECRET
--   - Content-Type: application/json

-- =============================================================================  
-- 7. RATE LIMITING
-- =============================================================================

-- Email rate limits:
-- - Password reset: 5 per hour per email
-- - Email confirmation: 3 per hour per email
-- - Magic link: 5 per hour per email

-- Sign up rate limits:
-- - 10 signups per hour per IP address
-- - 100 signups per day per IP address

-- =============================================================================
-- 8. DATABASE SETUP
-- =============================================================================

-- Enable RLS on auth schema (Supabase handles this automatically)
-- Custom user profiles stored in public.users table (see migrations/)
-- Session management handled by Supabase Auth

-- =============================================================================
-- 9. ENVIRONMENT VARIABLES REQUIRED
-- =============================================================================

-- Backend (.env):
-- SUPABASE_URL=https://your-project-ref.supabase.co
-- SUPABASE_ANON_KEY=your-anon-public-key  
-- SUPABASE_SERVICE_ROLE_KEY=your-service-role-secret-key
-- SUPABASE_JWT_SECRET=your-jwt-secret-for-verification

-- Frontend (.env.local):
-- NEXT_PUBLIC_SUPABASE_URL=https://your-project-ref.supabase.co
-- NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-public-key