"""Add type and books_sources to module_units; reseed all 15 modules

Revision ID: 013_add_type_books_sources
Revises: 0d1135672916
Create Date: 2026-04-01

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "013_add_type_books_sources"
down_revision: str | None = "0d1135672916"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "module_units",
        sa.Column("unit_type", sa.String(20), server_default="lesson", nullable=False),
    )
    op.add_column(
        "module_units",
        sa.Column("books_sources", sa.JSON(), nullable=True),
    )

    # Delete existing M01-M03 seed rows (will reseed below with full data)
    op.execute("DELETE FROM module_units")

    # Full seed: all 15 modules, each with lessons + quiz + case_study units
    op.execute("""
        WITH
          m01 AS (SELECT id FROM modules WHERE module_number = 1),
          m02 AS (SELECT id FROM modules WHERE module_number = 2),
          m03 AS (SELECT id FROM modules WHERE module_number = 3),
          m04 AS (SELECT id FROM modules WHERE module_number = 4),
          m05 AS (SELECT id FROM modules WHERE module_number = 5),
          m06 AS (SELECT id FROM modules WHERE module_number = 6),
          m07 AS (SELECT id FROM modules WHERE module_number = 7),
          m08 AS (SELECT id FROM modules WHERE module_number = 8),
          m09 AS (SELECT id FROM modules WHERE module_number = 9),
          m10 AS (SELECT id FROM modules WHERE module_number = 10),
          m11 AS (SELECT id FROM modules WHERE module_number = 11),
          m12 AS (SELECT id FROM modules WHERE module_number = 12),
          m13 AS (SELECT id FROM modules WHERE module_number = 13),
          m14 AS (SELECT id FROM modules WHERE module_number = 14),
          m15 AS (SELECT id FROM modules WHERE module_number = 15)
        INSERT INTO module_units
          (module_id, unit_number, title_fr, title_en, description_fr, description_en,
           estimated_minutes, order_index, unit_type, books_sources)
        VALUES
        -- M01: Fondements de la Santé Publique
        ((SELECT id FROM m01), 'M01-U01',
         'Définitions et histoire de la santé publique',
         'Definitions and history of public health',
         'Évolution de la santé publique, définitions OMS/Donaldson, cadre conceptuel moderne',
         'Evolution of public health, WHO/Donaldson definitions, modern conceptual framework',
         45, 1, 'lesson',
         '{"donaldson": ["Ch.1", "Ch.13"], "scutchfield": ["Ch.1", "Ch.2"]}'::json),

        ((SELECT id FROM m01), 'M01-U02',
         'Déterminants de santé et modèle Dahlgren-Whitehead',
         'Health determinants and Dahlgren-Whitehead model',
         'Le modèle des déterminants sociaux de santé contextualisé Afrique de l''Ouest',
         'Social determinants of health model contextualized for West Africa',
         50, 2, 'lesson',
         '{"donaldson": ["Ch.1"], "scutchfield": ["Ch.3", "Ch.4"]}'::json),

        ((SELECT id FROM m01), 'M01-U03',
         'Fonctions essentielles de santé publique en AOF',
         'Essential public health functions in West Africa',
         'Les 10 fonctions essentielles, cadre institutionnel OOAS/WAHO/CEDEAO',
         'The 10 essential functions, WAHO/ECOWAS institutional framework',
         50, 3, 'lesson',
         '{"donaldson": ["Ch.13"], "scutchfield": ["Ch.4"]}'::json),

        ((SELECT id FROM m01), 'M01-U04',
         'Quiz pratique : Fondements',
         'Practice Quiz: Foundations',
         'Testez votre compréhension des fondements de la santé publique',
         'Test your understanding of public health fundamentals',
         25, 4, 'quiz',
         '{"donaldson": ["Ch.1", "Ch.13"], "scutchfield": ["Ch.1", "Ch.2", "Ch.3", "Ch.4"]}'::json),

        ((SELECT id FROM m01), 'M01-U05',
         'Étude de cas : Épidémie Ebola Guinée 2014',
         'Case Study: Ebola Epidemic Guinea 2014',
         'Analyser les défaillances systémiques et proposer des mesures préventives',
         'Analyze systemic failures and propose preventive measures',
         40, 5, 'case-study',
         '{"donaldson": ["Ch.1", "Ch.13"], "scutchfield": ["Ch.1"]}'::json),

        -- M02: Introduction aux Données de Santé
        ((SELECT id FROM m02), 'M02-U01',
         'Types de données et sources en santé publique',
         'Data types and sources in public health',
         'Données nominales, ordinales, continues, discrètes; sources DHIS2, DHS, SNIS',
         'Nominal, ordinal, continuous, discrete data; DHIS2, DHS, NHIS sources',
         45, 1, 'lesson',
         '{"triola": ["Ch.1", "Ch.2"], "scutchfield": ["Ch.13"]}'::json),

        ((SELECT id FROM m02), 'M02-U02',
         'Statistiques descriptives appliquées à la santé',
         'Descriptive statistics applied to health',
         'Mesures de tendance centrale, dispersion, boxplots, valeurs aberrantes',
         'Measures of central tendency, dispersion, boxplots, outliers',
         55, 2, 'lesson',
         '{"triola": ["Ch.2", "Ch.3"]}'::json),

        ((SELECT id FROM m02), 'M02-U03',
         'Indicateurs de santé et interprétation',
         'Health indicators and interpretation',
         'Taux, ratios, proportions; indicateurs clés RMNCH; introduction Excel/Sheets',
         'Rates, ratios, proportions; key RMNCH indicators; intro Excel/Sheets',
         50, 3, 'lesson',
         '{"triola": ["Ch.3"], "scutchfield": ["Ch.13"], "donaldson": ["Ch.2"]}'::json),

        ((SELECT id FROM m02), 'M02-U04',
         'Quiz pratique : Données de santé',
         'Practice Quiz: Health Data',
         'Testez votre compréhension des types de données et statistiques de base',
         'Test your understanding of data types and basic statistics',
         25, 4, 'quiz',
         '{"triola": ["Ch.1", "Ch.2", "Ch.3"], "scutchfield": ["Ch.13"]}'::json),

        ((SELECT id FROM m02), 'M02-U05',
         'Exercice pratique : Analyse données paludisme Niger 2023',
         'Practical Exercise: Niger Malaria Data Analysis 2023',
         'Créer histogramme et boxplot, rédiger un rapport d''analyse',
         'Create histogram and boxplot, write an analysis report',
         40, 5, 'case-study',
         '{"triola": ["Ch.2", "Ch.3"]}'::json),

        -- M03: Systèmes de Santé en Afrique de l''Ouest
        ((SELECT id FROM m03), 'M03-U01',
         'Les 6 piliers OMS des systèmes de santé',
         'WHO 6 building blocks of health systems',
         'Gouvernance, financement, RH, médicaments, information sanitaire, prestation',
         'Governance, financing, human resources, medicines, health information, service delivery',
         45, 1, 'lesson',
         '{"donaldson": ["Ch.6"], "scutchfield": ["Ch.6", "Ch.7"]}'::json),

        ((SELECT id FROM m03), 'M03-U02',
         'Financement de la santé et couverture santé universelle',
         'Health financing and universal health coverage',
         'Modèles de financement; CSU en AOF; NHIS Ghana, CMU Sénégal',
         'Financing models; UHC in West Africa; Ghana NHIS, Senegal CMU',
         50, 2, 'lesson',
         '{"donaldson": ["Ch.6"], "scutchfield": ["Ch.8", "Ch.28"]}'::json),

        ((SELECT id FROM m03), 'M03-U03',
         'Défis et innovations des systèmes de santé AOF',
         'Challenges and innovations in West African health systems',
         'Défis actuels, secteur privé, rôle des ONG, indicateurs de performance JCI/WHO',
         'Current challenges, private sector, NGO role, JCI/WHO performance indicators',
         40, 3, 'lesson',
         '{"scutchfield": ["Ch.28"]}'::json),

        ((SELECT id FROM m03), 'M03-U04',
         'Quiz pratique : Systèmes de santé',
         'Practice Quiz: Health Systems',
         'Testez votre compréhension des systèmes de santé en AOF',
         'Test your understanding of health systems in West Africa',
         25, 4, 'quiz',
         '{"donaldson": ["Ch.6"], "scutchfield": ["Ch.6", "Ch.7", "Ch.8", "Ch.28"]}'::json),

        ((SELECT id FROM m03), 'M03-U05',
         'Étude comparative : NHIS Ghana comme modèle CSU en AOF',
         'Comparative Study: Ghana NHIS as UHC model in West Africa',
         'Analyse comparée des politiques de santé : Ghana, Sénégal, Nigeria, Mali',
         'Comparative analysis of health policies: Ghana, Senegal, Nigeria, Mali',
         40, 5, 'case-study',
         '{"donaldson": ["Ch.6"], "scutchfield": ["Ch.28"]}'::json),

        -- M04: Épidémiologie Appliquée
        ((SELECT id FROM m04), 'M04-U01',
         'Mesures de morbidité et mortalité',
         'Measures of morbidity and mortality',
         'Incidence cumulée, taux d''incidence, prévalence; TMG, TMI, TMM, espérance de vie',
         'Cumulative incidence, incidence rate, prevalence; CMR, IMR, MMR, life expectancy',
         55, 1, 'lesson',
         '{"donaldson": ["Ch.2"], "scutchfield": ["Ch.11"]}'::json),

        ((SELECT id FROM m04), 'M04-U02',
         'Design des études épidémiologiques',
         'Epidemiological study designs',
         'Études cohorte, cas-témoins, transversales; forces et limites; RR, OR, NNT',
         'Cohort, case-control, cross-sectional studies; strengths/limits; RR, OR, NNT',
         55, 2, 'lesson',
         '{"donaldson": ["Ch.2"], "scutchfield": ["Ch.13"]}'::json),

        ((SELECT id FROM m04), 'M04-U03',
         'DALY, biais et investigation d''épidémie',
         'DALY, bias and outbreak investigation',
         'AVCI/DALY, biais, facteurs de confusion; étapes OMS investigation terrain',
         'DALY, bias, confounding factors; WHO field investigation steps',
         50, 3, 'lesson',
         '{"donaldson": ["Ch.2"]}'::json),

        ((SELECT id FROM m04), 'M04-U04',
         'Quiz pratique : Épidémiologie',
         'Practice Quiz: Epidemiology',
         'Calculs d''incidence/prévalence, choix de design d''étude, interprétation RR/OR',
         'Incidence/prevalence calculations, study design choice, RR/OR interpretation',
         25, 4, 'quiz',
         '{"donaldson": ["Ch.2"], "scutchfield": ["Ch.11", "Ch.13"]}'::json),

        ((SELECT id FROM m04), 'M04-U05',
         'Simulation : Investigation épidémie choléra Niger',
         'Simulation: Cholera Outbreak Investigation Niger',
         'Jouer le rôle d''épidémiologiste OMS; données réelles OCHA/WHO 2022',
         'Play the role of WHO epidemiologist; real OCHA/WHO 2022 data',
         50, 5, 'case-study',
         '{"donaldson": ["Ch.2"]}'::json),

        -- M05: Biostatistiques pour la Santé Publique
        ((SELECT id FROM m05), 'M05-U01',
         'Probabilités et taux en santé',
         'Probabilities and health rates',
         'Théorème de Bayes, sensibilité/spécificité, VPP/VPN; taux mortalité/fécondité',
         'Bayes theorem, sensitivity/specificity, PPV/NPV; mortality/fertility rates',
         55, 1, 'lesson',
         '{"triola": ["Ch.4", "Ch.5"]}'::json),

        ((SELECT id FROM m05), 'M05-U02',
         'Distributions de probabilité et inférence',
         'Probability distributions and inference',
         'Distribution normale, binomiale, Poisson; TLC; intervalles de confiance IC95%',
         'Normal, binomial, Poisson distributions; CLT; 95% confidence intervals',
         55, 2, 'lesson',
         '{"triola": ["Ch.5", "Ch.6", "Ch.7"]}'::json),

        ((SELECT id FROM m05), 'M05-U03',
         'Tests d''hypothèse et taille d''échantillon',
         'Hypothesis testing and sample size',
         'H0/H1, erreur α/β, puissance; tests t, z, chi-carré; taille d''échantillon',
         'H0/H1, α/β error, power; t, z, chi-square tests; sample size calculation',
         55, 3, 'lesson',
         '{"triola": ["Ch.8", "Ch.9"]}'::json),

        ((SELECT id FROM m05), 'M05-U04',
         'Quiz pratique : Biostatistiques',
         'Practice Quiz: Biostatistics',
         'Calculs de probabilités, IC, tests d''hypothèse appliqués à la santé',
         'Probability calculations, CI, hypothesis testing applied to health',
         25, 4, 'quiz',
         '{"triola": ["Ch.4", "Ch.5", "Ch.6", "Ch.7", "Ch.8", "Ch.9"]}'::json),

        ((SELECT id FROM m05), 'M05-U05',
         'Exercice pratique : Prévalence anémie Mali (données DHS)',
         'Practical Exercise: Anemia Prevalence Mali (DHS data)',
         'Estimer prévalence anémie femmes enceintes au Mali; calculer IC95%',
         'Estimate anemia prevalence in pregnant women in Mali; calculate 95% CI',
         45, 5, 'case-study',
         '{"triola": ["Ch.7", "Ch.8"]}'::json),

        -- M06: Maladies et Déterminants en AOF
        ((SELECT id FROM m06), 'M06-U01',
         'Double fardeau des maladies en Afrique de l''Ouest',
         'Double burden of disease in West Africa',
         'Maladies transmissibles + MNT; profil épidémiologique comparé CEDEAO',
         'Communicable + non-communicable diseases; comparative ECOWAS epidemiological profile',
         50, 1, 'lesson',
         '{"donaldson": ["Ch.3", "Ch.4"], "scutchfield": ["Ch.17", "Ch.22"]}'::json),

        ((SELECT id FROM m06), 'M06-U02',
         'Paludisme, VIH/SIDA et tuberculose en AOF',
         'Malaria, HIV/AIDS and tuberculosis in West Africa',
         'Épidémiologie, prévention, traitement; objectifs 95-95-95 VIH; TB-VIH',
         'Epidemiology, prevention, treatment; HIV 95-95-95 targets; TB-HIV coinfection',
         55, 2, 'lesson',
         '{"donaldson": ["Ch.3"], "scutchfield": ["Ch.22"]}'::json),

        ((SELECT id FROM m06), 'M06-U03',
         'MNT émergentes et déterminants sociaux en AOF',
         'Emerging NCDs and social determinants in West Africa',
         'HTA, diabète, cancers; nutrition/sécurité alimentaire; déterminants sociaux',
         'Hypertension, diabetes, cancers; nutrition/food security; social determinants',
         50, 3, 'lesson',
         '{"donaldson": ["Ch.4", "Ch.5"], "scutchfield": ["Ch.18", "Ch.25"]}'::json),

        ((SELECT id FROM m06), 'M06-U04',
         'Quiz pratique : Maladies et déterminants',
         'Practice Quiz: Diseases and determinants',
         'Testez votre connaissance du profil épidémiologique AOF',
         'Test your knowledge of the West African epidemiological profile',
         25, 4, 'quiz',
         '{"donaldson": ["Ch.3", "Ch.4", "Ch.5"], "scutchfield": ["Ch.17", "Ch.18", "Ch.22", "Ch.25"]}'::json),

        ((SELECT id FROM m06), 'M06-U05',
         'Analyse comparative : Charge paludisme Nigeria vs Sénégal',
         'Comparative Analysis: Malaria Burden Nigeria vs Senegal',
         'Analyser les indicateurs WHO AFRO 2023; facteurs de succès Sénégal',
         'Analyze WHO AFRO 2023 indicators; success factors in Senegal',
         40, 5, 'case-study',
         '{"donaldson": ["Ch.3"]}'::json),

        -- M07: Outils et Pratiques de Santé Publique
        ((SELECT id FROM m07), 'M07-U01',
         'Leadership en santé publique',
         'Leadership in public health',
         'Modèles de leadership Kouzes-Posner, situationnel; gestion d''équipe ressources-limitées',
         'Kouzes-Posner, situational leadership models; managing teams in resource-limited settings',
         45, 1, 'lesson',
         '{"scutchfield": ["Ch.9", "Ch.10"]}'::json),

        ((SELECT id FROM m07), 'M07-U02',
         'Évaluation communautaire et planification sanitaire',
         'Community assessment and health planning',
         'MAPP, PATCH; objectifs SMART; plan de santé communautaire',
         'MAPP, PATCH frameworks; SMART objectives; community health planning',
         50, 2, 'lesson',
         '{"scutchfield": ["Ch.11", "Ch.12"]}'::json),

        ((SELECT id FROM m07), 'M07-U03',
         'Performance, données de santé et comportement',
         'Performance, health data and behavior',
         'KPI santé publique; gestion des données; théories HBM, TTM, TPS',
         'Public health KPIs; data management; HBM, TTM, TPS behavioral theories',
         50, 3, 'lesson',
         '{"scutchfield": ["Ch.14", "Ch.15", "Ch.16"]}'::json),

        ((SELECT id FROM m07), 'M07-U04',
         'Quiz pratique : Outils de santé publique',
         'Practice Quiz: Public health tools',
         'Testez vos connaissances en leadership, planification et gestion des données',
         'Test your knowledge of leadership, planning and data management',
         25, 4, 'quiz',
         '{"scutchfield": ["Ch.9", "Ch.10", "Ch.11", "Ch.12", "Ch.14", "Ch.15", "Ch.16"]}'::json),

        ((SELECT id FROM m07), 'M07-U05',
         'Planification : Programme de santé district rural Burkina Faso',
         'Planning: Rural district health program Burkina Faso',
         'Élaborer un plan de santé communautaire avec données DHIS2 réelles',
         'Develop a community health plan with real DHIS2 data',
         50, 5, 'case-study',
         '{"scutchfield": ["Ch.11", "Ch.12"]}'::json),

        -- M08: Surveillance Épidémiologique Numérique
        ((SELECT id FROM m08), 'M08-U01',
         'Types de surveillance et systèmes IDSR',
         'Surveillance types and IDSR systems',
         'Surveillance passive, active, sentinelle, syndromique; IDSR AOF',
         'Passive, active, sentinel, syndromic surveillance; IDSR West Africa',
         50, 1, 'lesson',
         '{"donaldson": ["Ch.2", "Ch.3"], "scutchfield": ["Ch.13"]}'::json),

        ((SELECT id FROM m08), 'M08-U02',
         'DHIS2 pour la surveillance des maladies',
         'DHIS2 for disease surveillance',
         'Architecture DHIS2, saisie, agrégation, visualisation, tableaux de bord',
         'DHIS2 architecture, data entry, aggregation, visualization, dashboards',
         55, 2, 'lesson',
         '{"scutchfield": ["Ch.13"]}'::json),

        ((SELECT id FROM m08), 'M08-U03',
         'Go.Data, SORMAS et RSI pour les urgences sanitaires',
         'Go.Data, SORMAS and IHR for health emergencies',
         'Outils numériques gestion épidémies; RSI 2005; capacités IHR en AOF',
         'Digital outbreak management tools; IHR 2005; IHR capacities in West Africa',
         50, 3, 'lesson',
         '{"donaldson": ["Ch.3"]}'::json),

        ((SELECT id FROM m08), 'M08-U04',
         'Quiz pratique : Surveillance numérique',
         'Practice Quiz: Digital surveillance',
         'Testez votre compréhension des systèmes de surveillance en AOF',
         'Test your understanding of surveillance systems in West Africa',
         25, 4, 'quiz',
         '{"donaldson": ["Ch.2", "Ch.3"], "scutchfield": ["Ch.13"]}'::json),

        ((SELECT id FROM m08), 'M08-U05',
         'TP : Tableau de bord DHIS2 surveillance méningite Niger',
         'Lab: DHIS2 surveillance dashboard for meningitis Niger',
         'Configurer un tableau de bord DHIS2 fictif; analyser une flambée simulée',
         'Configure a fictional DHIS2 dashboard; analyze a simulated outbreak',
         55, 5, 'case-study',
         '{"scutchfield": ["Ch.13"]}'::json),

        -- M09: Statistiques Avancées et Analyse de Données
        ((SELECT id FROM m09), 'M09-U01',
         'Corrélation, régression linéaire et logistique',
         'Correlation, linear and logistic regression',
         'Pearson/Spearman, régression linéaire simple/multiple, régression logistique',
         'Pearson/Spearman, simple/multiple linear regression, logistic regression',
         60, 1, 'lesson',
         '{"triola": ["Ch.10"]}'::json),

        ((SELECT id FROM m09), 'M09-U02',
         'ANOVA et tests non-paramétriques',
         'ANOVA and non-parametric tests',
         'ANOVA à 1 facteur, Tukey post-hoc; Wilcoxon, Mann-Whitney, Kruskal-Wallis',
         'One-way ANOVA, Tukey post-hoc; Wilcoxon, Mann-Whitney, Kruskal-Wallis',
         55, 2, 'lesson',
         '{"triola": ["Ch.11", "Ch.12", "Ch.13"]}'::json),

        ((SELECT id FROM m09), 'M09-U03',
         'Analyse de survie Kaplan-Meier et R/Python',
         'Kaplan-Meier survival analysis and R/Python',
         'Tables de vie, Kaplan-Meier, log-rank test, Cox; introduction R/Python/STATA',
         'Life tables, Kaplan-Meier, log-rank test, Cox model; intro R/Python/STATA',
         60, 3, 'lesson',
         '{"triola": ["Ch.14"]}'::json),

        ((SELECT id FROM m09), 'M09-U04',
         'Quiz pratique : Statistiques avancées',
         'Practice Quiz: Advanced statistics',
         'Régression, ANOVA, tests non-paramétriques et analyse de survie',
         'Regression, ANOVA, non-parametric tests and survival analysis',
         25, 4, 'quiz',
         '{"triola": ["Ch.10", "Ch.11", "Ch.12", "Ch.13", "Ch.14"]}'::json),

        ((SELECT id FROM m09), 'M09-U05',
         'Projet : Déterminants mortalité infantile Sénégal (données DHS 2019)',
         'Project: Infant mortality determinants Senegal (DHS 2019 data)',
         'Régression logistique, ANOVA comparaison vaccination 5 pays, Kaplan-Meier VIH Ghana',
         'Logistic regression, ANOVA vaccination comparison 5 countries, Kaplan-Meier HIV Ghana',
         60, 5, 'case-study',
         '{"triola": ["Ch.10", "Ch.14"]}'::json),

        -- M10: Santé Numérique et HMIS
        ((SELECT id FROM m10), 'M10-U01',
         'Composantes d''un HMIS et DHIS2 avancé',
         'HMIS components and advanced DHIS2',
         'Architecture HMIS; configurer DHIS2 pour collecte et analyse de données de santé',
         'HMIS architecture; configure DHIS2 for health data collection and analysis',
         55, 1, 'lesson',
         '{"scutchfield": ["Ch.13"]}'::json),

        ((SELECT id FROM m10), 'M10-U02',
         'Standards d''interopérabilité et mHealth en AOF',
         'Interoperability standards and mHealth in West Africa',
         'HL7 FHIR, OpenHIE, OpenMRS, ODK; applications mHealth et impact AOF',
         'HL7 FHIR, OpenHIE, OpenMRS, ODK; mHealth applications and impact in West Africa',
         50, 2, 'lesson',
         '{"scutchfield": ["Ch.13"]}'::json),

        ((SELECT id FROM m10), 'M10-U03',
         'IA en santé, qualité des données et éthique',
         'AI in health, data quality and ethics',
         'Opportunités/risques IA pour la santé AOF; qualité, confidentialité, éthique',
         'AI opportunities/risks for West African health; quality, privacy, ethics',
         45, 3, 'lesson',
         '{"scutchfield": ["Ch.13"]}'::json),

        ((SELECT id FROM m10), 'M10-U04',
         'Quiz pratique : Santé numérique',
         'Practice Quiz: Digital health',
         'Testez vos connaissances HMIS, mHealth et interopérabilité',
         'Test your knowledge of HMIS, mHealth and interoperability',
         25, 4, 'quiz',
         '{"scutchfield": ["Ch.13"]}'::json),

        ((SELECT id FROM m10), 'M10-U05',
         'Étude de cas : Programme mHealth iCCM au Ghana',
         'Case Study: iCCM mHealth programme in Ghana',
         'Évaluation qualité données DHIS2 Bénin; projets IA santé AOF (Zipline, HealthMap)',
         'Evaluation of DHIS2 data quality in Benin; AI health projects in West Africa',
         45, 5, 'case-study',
         '{"scutchfield": ["Ch.13"]}'::json),

        -- M11: Santé Environnementale et One Health
        ((SELECT id FROM m11), 'M11-U01',
         'Changement climatique et santé en AOF',
         'Climate change and health in West Africa',
         'Impacts climatiques sur la santé; WASH; inondations Sahel 2024',
         'Climate health impacts; WASH; Sahel 2024 floods',
         50, 1, 'lesson',
         '{"donaldson": ["Ch.12"], "scutchfield": ["Ch.23"]}'::json),

        ((SELECT id FROM m11), 'M11-U02',
         'One Health et zoonoses en Afrique de l''Ouest',
         'One Health and zoonoses in West Africa',
         'Concept One Health; zoonoses prioritaires AOF; Initiative One Health CEDEAO',
         'One Health concept; priority zoonoses in West Africa; ECOWAS One Health Initiative',
         45, 2, 'lesson',
         '{"donaldson": ["Ch.12"]}'::json),

        ((SELECT id FROM m11), 'M11-U03',
         'Pollution, évaluation d''impact et WASH',
         'Pollution, impact assessment and WASH',
         'Qualité de l''air Dakar/Lagos; EIS/HIA; eau potable et assainissement AOF',
         'Air quality Dakar/Lagos; HIA methodology; drinking water and sanitation in West Africa',
         40, 3, 'lesson',
         '{"donaldson": ["Ch.12"], "scutchfield": ["Ch.23"]}'::json),

        ((SELECT id FROM m11), 'M11-U04',
         'Quiz pratique : Santé environnementale',
         'Practice Quiz: Environmental health',
         'Testez vos connaissances sur le changement climatique, One Health et WASH',
         'Test your knowledge of climate change, One Health and WASH',
         25, 4, 'quiz',
         '{"donaldson": ["Ch.12"], "scutchfield": ["Ch.23"]}'::json),

        ((SELECT id FROM m11), 'M11-U05',
         'Étude de cas : Impacts sanitaires des inondations Sahel 2024',
         'Case Study: Health impacts of Sahel 2024 floods',
         'Analyser les impacts Niger, Tchad, Sénégal; données AirQo Dakar',
         'Analyze impacts in Niger, Chad, Senegal; AirQo Dakar air quality data',
         40, 5, 'case-study',
         '{"donaldson": ["Ch.12"]}'::json),

        -- M12: Santé Maternelle, Infantile et Communautaire
        ((SELECT id FROM m12), 'M12-U01',
         'Continuum de soins SMNI et mortalité maternelle',
         'MNCH care continuum and maternal mortality',
         'Soins grossesse/accouchement/post-partum; les 3 retards Thaddeus & Maine; TMM AOF',
         'Pregnancy/childbirth/postpartum care; 3 delays by Thaddeus & Maine; MMR West Africa',
         55, 1, 'lesson',
         '{"donaldson": ["Ch.8"], "scutchfield": ["Ch.25"]}'::json),

        ((SELECT id FROM m12), 'M12-U02',
         'PTME, nutrition infantile et vaccination',
         'PMTCT, child nutrition and vaccination',
         'Protocoles PTME; allaitement, ANJE, MAS; PEV/EPI, couverture vaccination',
         'PMTCT protocols; breastfeeding, IYCF, SAM; EPI immunization coverage',
         55, 2, 'lesson',
         '{"donaldson": ["Ch.8"], "scutchfield": ["Ch.25"]}'::json),

        ((SELECT id FROM m12), 'M12-U03',
         'Agents de santé communautaires et modèles iCCM',
         'Community health workers and iCCM models',
         'Modèles ASC/CHW en AOF; CHPS Ghana; suivi indicateurs SMNI avec DHIS2',
         'CHW models in West Africa; Ghana CHPS; tracking MNCH indicators with DHIS2',
         45, 3, 'lesson',
         '{"scutchfield": ["Ch.25"]}'::json),

        ((SELECT id FROM m12), 'M12-U04',
         'Quiz pratique : Santé maternelle et infantile',
         'Practice Quiz: Maternal and child health',
         'Testez vos connaissances SMNI, PTME, nutrition et vaccination',
         'Test your knowledge of MNCH, PMTCT, nutrition and vaccination',
         25, 4, 'quiz',
         '{"donaldson": ["Ch.8"], "scutchfield": ["Ch.25"]}'::json),

        ((SELECT id FROM m12), 'M12-U05',
         'Analyse : Programme vaccination Sénégal — succès et leçons',
         'Analysis: Senegal vaccination programme — successes and lessons',
         'Couverture rougeole >95%; modèle ASC communautaires Ghana CHPS',
         'Measles coverage >95%; Ghana CHPS community health worker model',
         40, 5, 'case-study',
         '{"donaldson": ["Ch.8"]}'::json),

        -- M13: Leadership, Politique et Gouvernance
        ((SELECT id FROM m13), 'M13-U01',
         'Cycle des politiques de santé et acteurs d''influence',
         'Health policy cycle and influencing actors',
         'Analyse des politiques; stakeholders, force field, SWOT; gouvernance multiniveaux',
         'Policy analysis; stakeholders, force field, SWOT; multi-level governance',
         55, 1, 'lesson',
         '{"scutchfield": ["Ch.9", "Ch.16"], "donaldson": ["Ch.6", "Ch.7"]}'::json),

        ((SELECT id FROM m13), 'M13-U02',
         'Plaidoyer structuré et partenariats multi-acteurs',
         'Structured advocacy and multi-stakeholder partnerships',
         'Élaborer un plaidoyer pour une politique de santé; gérer partenariats ONG/privé',
         'Develop health policy advocacy; manage NGO/private sector partnerships',
         50, 2, 'lesson',
         '{"scutchfield": ["Ch.19", "Ch.29"]}'::json),

        ((SELECT id FROM m13), 'M13-U03',
         'Évaluation des politiques de santé',
         'Health policy evaluation',
         'Efficacité, équité, efficience; outils d''évaluation; qualité des soins',
         'Effectiveness, equity, efficiency; evaluation tools; quality of care',
         45, 3, 'lesson',
         '{"donaldson": ["Ch.7"], "scutchfield": ["Ch.16"]}'::json),

        ((SELECT id FROM m13), 'M13-U04',
         'Quiz pratique : Leadership et politique',
         'Practice Quiz: Leadership and policy',
         'Testez vos connaissances en gouvernance sanitaire et plaidoyer',
         'Test your knowledge of health governance and advocacy',
         25, 4, 'quiz',
         '{"scutchfield": ["Ch.9", "Ch.16", "Ch.19", "Ch.29"], "donaldson": ["Ch.6", "Ch.7"]}'::json),

        ((SELECT id FROM m13), 'M13-U05',
         'Simulation : Plaidoyer financement santé devant ministre Niger',
         'Simulation: Health financing advocacy before Niger minister',
         'Défendre une politique de financement basée sur l''impôt; analyse CSU AOF',
         'Defend a tax-based health financing policy; analysis of UHC progress in West Africa',
         50, 5, 'case-study',
         '{"scutchfield": ["Ch.9"]}'::json),

        -- M14: Recherche et Évaluation Avancées
        ((SELECT id FROM m14), 'M14-U01',
         'Formulation de questions de recherche et protocoles',
         'Research question formulation and protocols',
         'PICO/PECO; conception d''études opérationnelles; essais cliniques, quasi-expérimentaux',
         'PICO/PECO; operational research design; clinical trials, quasi-experimental',
         55, 1, 'lesson',
         '{"triola": ["Ch.7", "Ch.8"], "scutchfield": ["Ch.12"]}'::json),

        ((SELECT id FROM m14), 'M14-U02',
         'Revue systématique, méta-analyse et évaluation de programme',
         'Systematic review, meta-analysis and programme evaluation',
         'PRISMA, PubMed, Cochrane; forest plot, hétérogénéité; RE-AIM, CIPP',
         'PRISMA, PubMed, Cochrane; forest plot, heterogeneity; RE-AIM, CIPP frameworks',
         55, 2, 'lesson',
         '{"triola": ["Ch.9", "Ch.10"], "scutchfield": ["Ch.17"]}'::json),

        ((SELECT id FROM m14), 'M14-U03',
         'Analyse économique, éthique et rédaction scientifique',
         'Economic analysis, ethics and scientific writing',
         'Coût-efficacité, AVCI, seuil décision; éthique CAMES; format IMRAD',
         'Cost-effectiveness, DALY, decision threshold; CAMES ethics; IMRAD format',
         50, 3, 'lesson',
         '{"triola": ["Ch.14"], "scutchfield": ["Ch.17"]}'::json),

        ((SELECT id FROM m14), 'M14-U04',
         'Quiz pratique : Recherche et évaluation',
         'Practice Quiz: Research and evaluation',
         'Testez vos connaissances en méthodologie de recherche et évaluation',
         'Test your knowledge of research methodology and evaluation',
         25, 4, 'quiz',
         '{"triola": ["Ch.7", "Ch.8", "Ch.9", "Ch.10", "Ch.14"], "scutchfield": ["Ch.12", "Ch.17"]}'::json),

        ((SELECT id FROM m14), 'M14-U05',
         'Projet : Évaluation impact programme moustiquaires Nord Nigeria',
         'Project: Evaluation of bed net programme impact North Nigeria',
         'Design quasi-expérimental différence-en-différences; analyse DHIS2; rédaction article',
         'Difference-in-differences quasi-experimental design; DHIS2 analysis; article writing',
         60, 5, 'case-study',
         '{"triola": ["Ch.7", "Ch.8"]}'::json),

        -- M15: Projet Intégratif Capstone
        ((SELECT id FROM m15), 'M15-U01',
         'Analyse de situation épidémiologique et déterminants',
         'Epidemiological situation analysis and determinants',
         'Analyser la situation d''un district AOF réel avec données DHIS2/DHS',
         'Analyze the situation of a real AOF district with DHIS2/DHS data',
         60, 1, 'lesson',
         '{"donaldson": ["Ch.1", "Ch.2"], "triola": ["Ch.1"], "scutchfield": ["Ch.1"]}'::json),

        ((SELECT id FROM m15), 'M15-U02',
         'Analyse statistique et revue de littérature',
         'Statistical analysis and literature review',
         'Appliquer les méthodes statistiques; revue de littérature des interventions efficaces',
         'Apply statistical methods; literature review of effective interventions',
         60, 2, 'lesson',
         '{"triola": ["Ch.10", "Ch.14"]}'::json),

        ((SELECT id FROM m15), 'M15-U03',
         'Plan d''intervention et tableau de bord DHIS2',
         'Intervention plan and DHIS2 dashboard',
         'Stratégie d''intervention basée sur les données; tableau de bord DHIS2',
         'Evidence-based intervention strategy; DHIS2 monitoring dashboard',
         60, 3, 'lesson',
         '{"scutchfield": ["Ch.11", "Ch.12", "Ch.13"]}'::json),

        ((SELECT id FROM m15), 'M15-U04',
         'Faisabilité, analyse économique et brief politique',
         'Feasibility, economic analysis and policy brief',
         'Analyse de faisabilité; analyse économique; brief politique (2 pages)',
         'Feasibility analysis; economic analysis; 2-page policy brief',
         55, 4, 'lesson',
         '{"scutchfield": ["Ch.17"], "triola": ["Ch.14"]}'::json),

        ((SELECT id FROM m15), 'M15-U05',
         'Projet Capstone Final : Présentation et défense',
         'Final Capstone Project: Presentation and defense',
         'Présenter les recommandations sous forme de brief politique et présentation orale',
         'Present recommendations as policy brief and oral presentation',
         90, 5, 'case-study',
         '{"donaldson": ["Ch.1", "Ch.2", "Ch.3", "Ch.4", "Ch.5", "Ch.6", "Ch.7", "Ch.8", "Ch.12", "Ch.13"], "scutchfield": ["Ch.1", "Ch.9", "Ch.11", "Ch.13", "Ch.17"], "triola": ["Ch.1", "Ch.10", "Ch.14"]}'::json)
    """)


def downgrade() -> None:
    op.execute("DELETE FROM module_units")
    op.drop_column("module_units", "books_sources")
    op.drop_column("module_units", "unit_type")
